// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1p6rTbtJjMWn53924l2WG7XzSYgavvi4',
    appId: '1:871246371401:web:3aecd42806db96e0713d98',
    messagingSenderId: '871246371401',
    projectId: 'to-do-list-app-37d1c',
    authDomain: 'to-do-list-app-37d1c.firebaseapp.com',
    storageBucket: 'to-do-list-app-37d1c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB84i5K-3ec6e_UOMta4nfm-ACgt27CR5k',
    appId: '1:871246371401:android:1012253549ce6e9f713d98',
    messagingSenderId: '871246371401',
    projectId: 'to-do-list-app-37d1c',
    storageBucket: 'to-do-list-app-37d1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaKEi_YLvQR7RrYCVBt3J7v3m0pQDP9u4',
    appId: '1:871246371401:ios:fd61e2353dfda79e713d98',
    messagingSenderId: '871246371401',
    projectId: 'to-do-list-app-37d1c',
    storageBucket: 'to-do-list-app-37d1c.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaKEi_YLvQR7RrYCVBt3J7v3m0pQDP9u4',
    appId: '1:871246371401:ios:fd61e2353dfda79e713d98',
    messagingSenderId: '871246371401',
    projectId: 'to-do-list-app-37d1c',
    storageBucket: 'to-do-list-app-37d1c.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1p6rTbtJjMWn53924l2WG7XzSYgavvi4',
    appId: '1:871246371401:web:45c545ed2473e36a713d98',
    messagingSenderId: '871246371401',
    projectId: 'to-do-list-app-37d1c',
    authDomain: 'to-do-list-app-37d1c.firebaseapp.com',
    storageBucket: 'to-do-list-app-37d1c.appspot.com',
  );
}
